name: codecov--onPublished

on:
  release:
    types:
      - published

jobs:
  codecov--onPublished:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: npm -g i pnpm

      - run: pnpm i --frozen-lockfile --ignore-scripts

      - run: pnpm test:cov

      - uses: codecov/codecov-action@master
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
