name: docker-build-push-gpr

on:
  push:
    branches:
      - 'releases/**'

jobs:

  run:
    runs-on: ubuntu-latest 
    steps:

    - name: git checkout
      uses: actions/checkout@master

    - name: docker build push
      uses: docker/build-push-action@v1
      with:
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ GITHUB_REPOSITORY }}
        tags: latest

     #This Action Emits 2 Variables, IMAGE_SHA_NAME and IMAGE_URL 
     #which you can reference in subsequent steps
    # - name: Publish Docker Image to GPR
    #   uses: machine-learning-apps/gpr-docker-publish@master
    #   id: docker
    #   with:
    #     IMAGE_NAME: 'master'
    #     TAG: 'latest'
    #     DOCKERFILE_PATH: 'Dockerfile'
    #     BUILD_CONTEXT: '.'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # This second step is illustrative and shows how to reference the 
    # output variables.  This is completely optional.
    # - name: Show outputs of previous step
    #   run: |
    #     echo "The name:tag of the Docker Image is: $VAR1"
    #     echo "The docker image is hosted at $VAR2"
    #   env:
    #     VAR1: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
    #     VAR2: ${{ steps.docker.outputs.IMAGE_URL }}
