name: yarn-upgrade

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:

  run:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: yarn upgrade --latest

      - run: |
          git config --global user.email "asfalte@bamdadsabbagh.com"
          git config --global user.name "asfalte"

      - run: |
          git add .
          git commit -m "fix: auto upgrade to latest"
      
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
